name: Build CuriousMind JAR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven (includes tests)
        working-directory: Java
        run: mvn clean package -DskipTests

      - name: Copy JAR to artifacts folder
        run: |
          mkdir -p java/target/artifacts
          cp java/target/*.jar java/target/artifacts

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: CuriousMind
          path: Java/target/artifacts/*.jar
